//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abazov_ShutAndKrol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShutAndKrolEntities : DbContext
    {
        public ShutAndKrolEntities()
            : base("name=ShutAndKrolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ReadingLists> ReadingLists { get; set; }
        public virtual DbSet<ReadingListStatuses> ReadingListStatuses { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<RoleRequests> RoleRequests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<View_ActiveAuthors> View_ActiveAuthors { get; set; }
        public virtual DbSet<View_PopularBooks> View_PopularBooks { get; set; }
        public virtual DbSet<View_ProblemContent> View_ProblemContent { get; set; }
        public virtual DbSet<View_ReviewComplaints> View_ReviewComplaints { get; set; }
        public virtual DbSet<View_UserStatistics> View_UserStatistics { get; set; }
    }
}
