//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abazov_ShutAndKrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProblemContent
    {
        public string BookTitle { get; set; }
        public Nullable<int> ComplaintsCount { get; set; }
    }
}
