//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abazov_ShutAndKrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserStatistics
    {
        public string Login { get; set; }
        public string DisplayName { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> BooksInList { get; set; }
    }
}
